<?php

namespace Container06Nsgwt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuestionDropdownValuesControllerService extends Glpi_Kernel_KernelProductionContainer
{
    /*
     * Gets the public 'Glpi\Controller\Form\QuestionDropdownValuesController' shared autowired service.
     *
     * @return \Glpi\Controller\Form\QuestionDropdownValuesController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Glpi\\Controller\\Form\\QuestionDropdownValuesController'] = new \Glpi\Controller\Form\QuestionDropdownValuesController();
    }
}
