<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3Jcx2Wn\Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3Jcx2Wn/Glpi_Kernel_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/Container3Jcx2Wn.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    \class_alias(\Container3Jcx2Wn\Glpi_Kernel_KernelProductionDebugContainer::class, Glpi_Kernel_KernelProductionDebugContainer::class, false);
}

return new \Container3Jcx2Wn\Glpi_Kernel_KernelProductionDebugContainer([
    'container.build_hash' => '3Jcx2Wn',
    'container.build_id' => '3d4a5a9d',
    'container.build_time' => 1780485719,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3Jcx2Wn');
