<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGCxQa1s\Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGCxQa1s/Glpi_Kernel_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/ContainerGCxQa1s.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    \class_alias(\ContainerGCxQa1s\Glpi_Kernel_KernelProductionDebugContainer::class, Glpi_Kernel_KernelProductionDebugContainer::class, false);
}

return new \ContainerGCxQa1s\Glpi_Kernel_KernelProductionDebugContainer([
    'container.build_hash' => 'GCxQa1s',
    'container.build_id' => '4cc460ae',
    'container.build_time' => 1781010312,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGCxQa1s');
