<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9bmRhHu\Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9bmRhHu/Glpi_Kernel_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/Container9bmRhHu.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    \class_alias(\Container9bmRhHu\Glpi_Kernel_KernelProductionDebugContainer::class, Glpi_Kernel_KernelProductionDebugContainer::class, false);
}

return new \Container9bmRhHu\Glpi_Kernel_KernelProductionDebugContainer([
    'container.build_hash' => '9bmRhHu',
    'container.build_id' => 'b61a002f',
    'container.build_time' => 1780892373,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9bmRhHu');
