<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4NXW7xe\Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4NXW7xe/Glpi_Kernel_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/Container4NXW7xe.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    \class_alias(\Container4NXW7xe\Glpi_Kernel_KernelProductionDebugContainer::class, Glpi_Kernel_KernelProductionDebugContainer::class, false);
}

return new \Container4NXW7xe\Glpi_Kernel_KernelProductionDebugContainer([
    'container.build_hash' => '4NXW7xe',
    'container.build_id' => 'd6d0611b',
    'container.build_time' => 1780491691,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4NXW7xe');
