<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIrxop6q\Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIrxop6q/Glpi_Kernel_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/ContainerIrxop6q.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    \class_alias(\ContainerIrxop6q\Glpi_Kernel_KernelProductionDebugContainer::class, Glpi_Kernel_KernelProductionDebugContainer::class, false);
}

return new \ContainerIrxop6q\Glpi_Kernel_KernelProductionDebugContainer([
    'container.build_hash' => 'Irxop6q',
    'container.build_id' => '74d50610',
    'container.build_time' => 1780494708,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIrxop6q');
